apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upgrade-sample
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem