# Copyright Contributors to the Open Cluster Management project
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterhub-catalog
  namespace: default
spec:
  displayName: MultiCluster Hub
  publisher: Red Hat
  sourceType: grpc
  image: "quay.io/cameronmwall/catalog-rep:downstream-n"
  updateStrategy:
    registryPoll:
      interval: 10m
