# Copyright Contributors to the Open Cluster Management project
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterhub-catalog
  namespace: default
spec:
  displayName: MultiCluster Hub
  publisher: Red Hat
  sourceType: grpc
  image: "quay.io/open-cluster-management/acm-custom-registry:2.3.0-SNAPSHOT-2021-07-30-16-12-20"
  updateStrategy:
    registryPoll:
      interval: 10m
